# Generated by ChatGPT for initial models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name='NewsSource',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('title', models.CharField(blank=True, max_length=255)),
				('url', models.URLField(unique=True)),
				('is_active', models.BooleanField(default=True)),
			],
		),
		migrations.CreateModel(
			name='NewsItem',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('title', models.CharField(max_length=500)),
				('original_url', models.URLField(unique=True)),
				('description', models.TextField(blank=True)),
				('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
				('source_name', models.CharField(blank=True, max_length=255)),
			],
		),
		migrations.CreateModel(
			name='AuthorColumn',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('title', models.CharField(max_length=500)),
				('author_name', models.CharField(max_length=255)),
				('content_body', models.TextField()),
				('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
			],
		),
		migrations.CreateModel(
			name='OutboxEvent',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('event_type', models.CharField(choices=[('news.created', 'News created'), ('column.created', 'Column created')], max_length=64)),
				('payload', models.JSONField()),
				('delivered_at', models.DateTimeField(blank=True, null=True)),
				('delivery_attempts', models.PositiveIntegerField(default=0)),
				('last_error', models.TextField(blank=True)),
			],
		),
		migrations.AddIndex(
			model_name='outboxevent',
			index=models.Index(fields=['created_at'], name='core_outbox_created_9dfbd1_idx'),
		),
	]


