# Generated by Django 5.0.7 on 2025-09-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegramchannel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='core_outbox_created_afd1b7_idx',
            old_name='core_outbox_created_9dfbd1_idx',
        ),
    ]
