# Generated by Django 5.0.7 on 2025-10-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_keywordfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcolumn',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='columns/'),
        ),
        migrations.AddField(
            model_name='authorcolumn',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
