# Generated by Django 5.0.7 on 2025-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_parserconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserconfig',
            name='min_chars',
            field=models.PositiveIntegerField(default=0, help_text='Skip posts shorter than this many characters (0 to disable)'),
        ),
    ]
