# Generated by Django 5.0.7 on 2025-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_parserconfig_min_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserconfig',
            name='image_quality',
            field=models.PositiveIntegerField(default=85, help_text='JPEG/WebP quality 1-95'),
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='max_image_height',
            field=models.PositiveIntegerField(default=720, help_text='Max image height in pixels (0 to disable)'),
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='max_image_width',
            field=models.PositiveIntegerField(default=1280, help_text='Max image width in pixels (0 to disable)'),
        ),
    ]
