# Generated by Django 5.0.7 on 2025-10-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_parserconfig_image_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcolumn',
            name='theme',
            field=models.CharField(choices=[('AI', 'AI'), ('CRYPTO', 'CRYPTO')], db_index=True, default='AI', max_length=16),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='theme',
            field=models.CharField(choices=[('AI', 'AI'), ('CRYPTO', 'CRYPTO')], db_index=True, default='AI', max_length=16),
        ),
        migrations.AddField(
            model_name='newssource',
            name='default_theme',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('CRYPTO', 'CRYPTO')], max_length=16),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='default_theme',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('CRYPTO', 'CRYPTO')], max_length=16),
        ),
        migrations.AddField(
            model_name='websitesource',
            name='default_theme',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('CRYPTO', 'CRYPTO')], max_length=16),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='core_hashta_slug_155ef9_idx')],
            },
        ),
        migrations.AddField(
            model_name='authorcolumn',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='author_columns', to='core.hashtag'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='core.hashtag'),
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='core_sitepa_slug_2d7bd1_idx')],
            },
        ),
    ]
