# Generated by Django 5.0.7 on 2025-10-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='parse_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='parse_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitesource',
            name='parse_images',
            field=models.BooleanField(default=True),
        ),
    ]
