# Generated by Django 5.0.7 on 2025-10-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='ads/')),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='newssource',
            name='parse_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='parse_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitesource',
            name='parse_images',
            field=models.BooleanField(default=True),
        ),
    ]
