# Generated by Django 5.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_adclassifierconfig"),
    ]

    operations = [
        # Add Russian fields to NewsItem
        migrations.AddField(
            model_name="newsitem",
            name="title_ru",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="description_ru",
            field=models.TextField(blank=True),
        ),
        # Add Russian fields to AuthorColumn
        migrations.AddField(
            model_name="authorcolumn",
            name="title_ru",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="authorcolumn",
            name="content_body_ru",
            field=models.TextField(blank=True),
        ),
        # Create TranslatorConfig model
        migrations.CreateModel(
            name="TranslatorConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("model", models.CharField(default="gpt-4o-mini", max_length=64)),
                ("prompt", models.TextField(blank=True, help_text="System instructions for translating content from English to Russian. Must return JSON with keys 'title_ru' and 'content_ru'.")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]

